function collect_decision_blocks(rootDir, model, matFileName, initScripts, outputJson)
%COLLECT_DECISION_BLOCKS Collect decision blocks with real connectivity evidence.
%   Writes a `simulink-ut-decision-blocks/v1` JSON that the deterministic
%   Python side (build_decision_obligations.py --blocks) turns into Decision
%   obligations. The MATLAB model session is the authority here: block
%   parameters, SIDs, PortConnectivity, and traced upstream sources (root
%   Inport name or literal Constant value) are all resolved from the loaded
%   model instead of guessed from static XML.
%
%   Call pattern (entry script generated by the runner):
%     addpath(scriptsDir); setup_ut_support(rootDir, initScripts);
%     collect_decision_blocks(rootDir, model, matFileName, initScripts, outJson);

    load_mat_to_base(resolve_workspace_file(rootDir, matFileName));
    load_system(fullfile(rootDir, [model '.slx']));
    if exist('configure_tcsd_sim_config', 'file') == 2
        configure_tcsd_sim_config(model, rootDir);
    end
    rootInputs = root_input_names(model);
    allBlocks = find_system(model, 'LookUnderMasks', 'all', 'FollowLinks', 'on');

    targetTypes = {'Switch', 'RelationalOperator', 'MinMax', 'MultiPortSwitch', 'Saturate', 'Abs'};
    recs = struct('path', {}, 'sid', {}, 'type', {}, 'params', {}, 'inputs', {});
    gates = struct('path', {}, 'type', {}, 'inputs', {});
    for i = 1:numel(allBlocks)
        b = allBlocks{i};
        bt = safe_block_type(b);
        if ismember(bt, {'Enable', 'Trigger'})
            gates(end + 1) = collect_gate(b, rootInputs); %#ok<AGROW>
            continue;
        end
        if ~ismember(bt, targetTypes)
            continue;
        end
        rec = struct('path', b, 'sid', '', 'type', bt, 'params', struct(), 'inputs', struct());
        try
            rec.sid = char(string(get_param(b, 'SID')));
        catch
        end
        rec.params = collect_params(b, bt);
        inps = collect_inputs(b, rootInputs, 0);
        rec.inputs = inps(:).';
        recs(end + 1) = rec; %#ok<AGROW>
    end

    out = struct('schema', 'simulink-ut-decision-blocks/v1', 'model', model, ...
                 'root_inputs', {rootInputs}, 'blocks', recs, 'enable_ports', gates);
    write_json_file(outputJson, out);
    bdclose(model);
end

function ok = is_input_port(portType)
    ok = strcmpi(char(string(portType)), 'input') || strcmpi(char(string(portType)), 'inport');
end

function bt = safe_block_type(b)
    bt = '';
    try
        bt = get_param(b, 'BlockType');
    catch
    end
end

function names = root_input_names(model)
    names = {};
    try
        ins = find_system(model, 'SearchDepth', 1, 'BlockType', 'Inport');
        for i = 1:numel(ins)
            names{end + 1} = char(string(get_param(ins{i}, 'Name'))); %#ok<AGROW>
        end
    catch
    end
end

function params = collect_params(b, bt)
    params = struct();
    names = {};
    switch bt
        case 'Switch'
            names = {'Criteria', 'Threshold'};
        case 'RelationalOperator'
            names = {'Operator'};
        case 'MinMax'
            names = {'Function', 'Inputs'};
        case 'MultiPortSwitch'
            names = {'Inputs', 'DataPortOrder'};
        case 'Saturate'
            names = {'UpperLimit', 'LowerLimit'};
        case 'Abs'
            names = {};
    end
    for k = 1:numel(names)
        try
            params.(names{k}) = get_param(b, names{k});
        catch
        end
    end
end

function inputs = collect_inputs(b, rootInputs, depth)
    inputs = struct('port', {}, 'src_kind', {}, 'src_value', {}, ...
                    'src_param_min', {}, 'src_param_max', {}, 'src_param_value', {});
    try
        ph = get_param(b, 'PortHandles');
    catch
        return;
    end
    for port = 1:numel(ph.Inport)
        [kind, value] = trace_upstream_of_port(b, port, rootInputs, depth);
        entry = struct('port', port, 'src_kind', kind, 'src_value', value, ...
                       'src_param_min', [], 'src_param_max', [], 'src_param_value', []);
        if strcmp(kind, 'param')
            bounds = param_bounds(value);
            if ~isempty(bounds)
                entry.src_param_min = bounds.min;
                entry.src_param_max = bounds.max;
                entry.src_param_value = bounds.value;
            end
        end
        inputs(end + 1) = entry; %#ok<AGROW>
    end
end

function bounds = param_bounds(name)
    bounds = [];
    try
        obj = evalin('base', name);
    catch
        return;
    end
    if ~isobject(obj) && ~isprop(obj, 'Value')
        return;
    end
    bounds = struct('min', [], 'max', [], 'value', []);
    try
        bounds.value = obj.Value;
    catch
    end
    try
        bounds.min = obj.Min;
    catch
    end
    try
        bounds.max = obj.Max;
    catch
    end
end

function [kind, value] = trace_upstream_of_port(blockPath, port, rootInputs, depth)
    kind = 'unresolved';
    value = 'no_src';
    srcPath = upstream_block_of_port(blockPath, port);
    if isempty(srcPath)
        return;
    end
    [kind, value] = trace_upstream(srcPath, rootInputs, depth);
end

function up = upstream_block_of_port(blockPath, port)
    up = '';
    try
        ph = get_param(blockPath, 'PortHandles');
        if port >= 1 && port <= numel(ph.Inport)
            line = get_param(ph.Inport(port), 'Line');
            if ~isequal(line, -1)
                srcPort = get_param(line, 'SrcPortHandle');
                up = get_param(srcPort, 'Parent');
            end
        end
    catch
    end
end

function gate = collect_gate(b, rootInputs)
    inps = collect_inputs(b, rootInputs, 0);
    gate = struct('path', b, 'type', safe_block_type(b), 'inputs', inps(:).');
end

function [kind, value] = trace_upstream(srcPath, rootInputs, depth)
    kind = 'unresolved';
    value = 'trace_depth_exceeded';
    if depth > 8 || isempty(srcPath)
        if depth > 8
            return;
        end
        value = 'no_src';
        return;
    end
    try
        st = get_param(srcPath, 'BlockType');
    catch
        value = 'block_missing';
        return;
    end
    switch st
        case 'Inport'
            name = char(string(get_param(srcPath, 'Name')));
            if ismember(name, rootInputs)
                kind = 'input';
                value = name;
                return;
            end
            % Subsystem entry: resolve the parent block's upstream of port N.
            try
                portNo = char(string(get_param(srcPath, 'Port')));
            catch
                kind = 'unresolved';
                value = 'inport_port_missing';
                return;
            end
            parent = parent_of(srcPath);
            if isempty(parent)
                kind = 'unresolved';
                value = 'subsystem_entry_unknown_parent';
                return;
            end
            up = upstream_of(parent, str2double(portNo));
            [kind, value] = trace_upstream(up, rootInputs, depth + 1);
        case 'Constant'
            kind = 'const';
            try
                value = char(string(get_param(srcPath, 'Value')));
            catch
                value = '';
            end
            % Constant references a workspace calibration object: the value is
            % parameter-controlled, which the obligation builder maps to a
            % `p Param=value;` override instead of a root-input assignment.
            if ~isempty(value) && isempty(str2num(value)) && evalin('base', ['exist(''' value ''',''var'')'])
                kind = 'param';
            end
        case 'Goto'
            up = upstream_of(srcPath, 1);
            [kind, value] = trace_upstream(up, rootInputs, depth + 1);
        case 'From'
            tag = char(string(get_param(srcPath, 'GotoTag')));
            gotos = find_system(get_param(srcPath, 'Parent'), 'LookUnderMasks', 'all', ...
                                'FollowLinks', 'on', 'BlockType', 'Goto', 'GotoTag', tag);
            if numel(gotos) ~= 1
                kind = 'unresolved';
                value = 'goto_ambiguous_or_missing';
                return;
            end
            up = upstream_of(gotos{1}, 1);
            [kind, value] = trace_upstream(up, rootInputs, depth + 1);
        otherwise
            kind = 'unresolved';
            value = ['unsupported_src_type_' st];
    end
end

function parent = parent_of(blockPath)
    parent = '';
    parts = strsplit(blockPath, '/');
    if numel(parts) > 1
        parent = strjoin(parts(1:end - 1), '/');
    end
end

function up = upstream_of(blockPath, port)
    up = upstream_block_of_port(blockPath, port);
end

function filePath = resolve_workspace_file(rootDir, fileName)
    filePath = char(string(fileName));
    if ~isfile(filePath)
        filePath = fullfile(rootDir, filePath);
    end
end

function load_mat_to_base(matPath)
    if ~exist(matPath, 'file')
        return;
    end
    try
        vars = whos('-file', matPath);
        names = {vars.name};
        for i = 1:numel(names)
            try
                if ~evalin('base', ['exist(''' names{i} ''', ''var'')'])
                    data = load(matPath, names{i});
                    assignin('base', names{i}, data.(names{i}));
                end
            catch
            end
        end
    catch
    end
end

function write_json_file(pathName, data)
    fid = fopen(pathName, 'w');
    if fid < 0
        error('collect_decision_blocks:open', 'cannot open %s for writing', pathName);
    end
    fprintf(fid, '%s', jsonencode(data, 'PrettyPrint', true));
    fclose(fid);
    fprintf('Wrote %s\n', pathName);
end
