function probe_block_inputs_with_params(rootDir, model, matFileName, initScripts, probeJsonPath, outputJsonPath)
%PROBE_BLOCK_INPUTS_WITH_PARAMS Probe block input values under parameter overrides.
%   Runs one or more scenarios (root-input initial values, scalar parameter
%   overrides, ordered delay steps) and records, for every observed block, the
%   actual values on each input port at the final step, plus the model's root
%   Outport values. This is the deterministic counterpart of the manual
%   stage-10 probing the agent used to hand-write.
%
%   Input probeJson (schema simulink-ut-block-input-probe-request/v1):
%     {
%       "scenarios": [{
%         "id": "s1",
%         "initial_inputs": {"RngPrdn_bPrpElecCnsmnCalcEna": 1},
%         "initial_params": {"Max_C": 100},
%         "steps": [{"delay_s": 0.1, "input_updates": {"Sig": 2}}],
%         "sample_time": 0.01
%       }],
%       "observe_blocks": ["M/Sub/Switch3"]
%     }
%   Output (schema simulink-ut-block-input-probe/v1):
%     { "schema": ..., "model": ..., "scenarios": [{
%         "id", "ok", "error",
%         "block_observations": [{"path", "port", "value", "present"}],
%         "outputs": {"OutName": value} }] }
%
%   Call pattern (entry script generated by the runner):
%     addpath(scriptsDir); setup_ut_support(rootDir, initScripts);
%     probe_block_inputs_with_params(rootDir, model, mat, initScripts, reqJson, outJson);

    spec = jsondecode(fileread(probeJsonPath));
    load_mat_to_base(resolve_workspace_file(rootDir, matFileName));
    load_system(fullfile(rootDir, [model '.slx']));
    if exist('configure_tcsd_sim_config', 'file') == 2
        configure_tcsd_sim_config(model, rootDir);
    end
    [inputNames, inputBlocks, outputNames] = root_ports(model);
    [inputTypes, inputDims] = compiled_input_metadata(model, inputBlocks, inputNames);
    scenarios = normalize_struct_array(spec.scenarios);
    observeBlocks = parse_block_list(spec.observe_blocks);

    results = struct('id', {}, 'ok', {}, 'error', {}, 'block_observations', {}, 'outputs', {});
    fprintf('PROBE_DIAG scenarios=%d\n', numel(scenarios));
    for si = 1:numel(scenarios)
        sc = scenarios(si);
        results(end + 1).id = sc.id; %#ok<AGROW>
        fprintf('PROBE_DIAG scenario %d id=%s\n', si, char(string(sc.id)));
        probeBlocks = {};
        restore = struct();
        try
            initParams = ensure_struct(sc, 'initial_params');
            restore = snapshot_parameters(initParams);
            apply_parameter_overrides(initParams);
            [probeSpecs, probeBlocks] = add_input_probes(model, observeBlocks, si);
            [ds, stopTime] = build_dataset(inputNames, inputTypes, inputDims, ensure_struct(sc, 'initial_inputs'), normalize_struct_array(sc.steps));
            dt = default_sample_time(sc);
            in = Simulink.SimulationInput(model);
            in = in.setVariable('tc_sd_external_input_ds', ds);
            in = in.setModelParameter('StopTime', num2str(stopTime), ...
                'SolverType', 'Fixed-step', 'Solver', 'FixedStepDiscrete', 'FixedStep', num2str(dt), ...
                'SaveOutput', 'on', 'ReturnWorkspaceOutputs', 'on', ...
                'LoadExternalInput', 'on', 'ExternalInput', 'tc_sd_external_input_ds');
            out = sim(in);
            observations = collect_block_observations(out, probeSpecs);
            outputs = collect_root_outputs(out, outputNames);
            results(end).ok = true;
            results(end).error = '';
            results(end).block_observations = observations;
            results(end).outputs = outputs;
            fprintf('PROBE_DIAG scenario %d ok\n', si);
        catch ME
            fprintf('PROBE_DIAG scenario %d catch: %s\n', si, ME.message);
            results(end).ok = false;
            results(end).error = ME.message;
            results(end).block_observations = struct([]);
            results(end).outputs = struct();
        end
        remove_probe_blocks(probeBlocks);
        restore_parameters(restore);
    end

    report = struct('schema', 'simulink-ut-block-input-probe/v1', 'model', model, 'scenarios', results);
    write_json_file(outputJsonPath, report);
    bdclose(model);
end

function list = parse_block_list(value)
    if ischar(value) || isstring(value)
        list = {char(string(value))};
    else
        list = cellstr(string(value))';
    end
end

function dt = default_sample_time(sc)
    dt = 0.01;
    if isfield(sc, 'sample_time') && ~isempty(sc.sample_time)
        dt = double(sc.sample_time);
    end
end

function [inputNames, inputBlocks, outputNames] = root_ports(modelName)
    inputBlocks = find_system(modelName, 'SearchDepth', 1, 'BlockType', 'Inport');
    [~, inputOrder] = sort(str2double(get_param(inputBlocks, 'Port')));
    inputBlocks = inputBlocks(inputOrder);
    inputNames = cellfun(@(p) get_param(p, 'Name'), inputBlocks, 'UniformOutput', false);
    outputBlocks = find_system(modelName, 'SearchDepth', 1, 'BlockType', 'Outport');
    [~, outputOrder] = sort(str2double(get_param(outputBlocks, 'Port')));
    outputBlocks = outputBlocks(outputOrder);
    outputNames = cellfun(@(p) get_param(p, 'Name'), outputBlocks, 'UniformOutput', false);
end

function [inputTypes, inputDims] = compiled_input_metadata(modelName, inputBlocks, inputNames)
    inputTypes = struct();
    inputDims = struct();
    for i = 1:numel(inputNames)
        inputTypes.(inputNames{i}) = 'single';
        inputDims.(inputNames{i}) = 1;
    end
    try
        feval(modelName, [], [], [], 'compile');
        cleanupObj = onCleanup(@() feval(modelName, [], [], [], 'term'));
        for i = 1:numel(inputNames)
            portHandles = get_param(inputBlocks{i}, 'PortHandles');
            dtype = get_param(portHandles.Outport, 'CompiledPortDataType');
            dims = get_param(portHandles.Outport, 'CompiledPortDimensions');
            inputTypes.(inputNames{i}) = char(string(dtype));
            inputDims.(inputNames{i}) = compiled_width(dims);
        end
        clear cleanupObj;
    catch
    end
end

function width = compiled_width(dims)
    dims = double(dims);
    if isempty(dims)
        width = 1;
    elseif isscalar(dims)
        width = max(1, dims(1));
    elseif numel(dims) >= 2
        width = max(1, prod(dims(2:end)));
    else
        width = 1;
    end
end

function [ds, stopTime] = build_dataset(inputNames, inputTypes, inputDims, initValues, steps)
    dt = 0.01;
    currentValues = struct();
    for i = 1:numel(inputNames)
        currentValues.(inputNames{i}) = zeros(1, inputDims.(inputNames{i}));
    end
    initFields = fieldnames(initValues);
    for i = 1:numel(initFields)
        name = initFields{i};
        if isfield(inputDims, name)
            currentValues.(name) = normalize_input_value(initValues.(name), inputDims.(name));
        end
    end
    totalTime = 0;
    for k = 1:numel(steps)
        totalTime = totalTime + double(steps(k).delay_s);
    end
    stopTime = max(dt, ceil(totalTime / dt) * dt);
    t = (0:dt:stopTime)';
    seriesData = struct();
    for k = 1:numel(inputNames)
        name = inputNames{k};
        seriesData.(name) = repmat(currentValues.(name), numel(t), 1);
    end
    currentTime = 0;
    for k = 1:numel(steps)
        currentTime = currentTime + double(steps(k).delay_s);
        updates = ensure_struct(steps(k), 'input_updates');
        fields = fieldnames(updates);
        sampleMask = t >= (currentTime - (dt / 100));
        for j = 1:numel(fields)
            name = fields{j};
            if isfield(seriesData, name)
                value = normalize_input_value(updates.(name), inputDims.(name));
                seriesData.(name)(sampleMask, :) = repmat(value, sum(sampleMask), 1);
                currentValues.(name) = value;
            end
        end
    end
    ds = Simulink.SimulationData.Dataset;
    for k = 1:numel(inputNames)
        name = inputNames{k};
        data = cast_input_for_simulink_ut(seriesData.(name), inputTypes.(name));
        if inputDims.(name) == 1
            data = data(:, 1);
        end
        ts = timeseries(data, t);
        ts.Name = name;
        try
            ts = setinterpmethod(ts, 'zoh');
        catch
        end
        ds{k} = ts;
    end
end

function [probeSpecs, probeBlocks] = add_input_probes(modelName, observeBlocks, scenarioIndex)
    probeSpecs = struct('path', {}, 'port', {}, 'variable', {});
    probeBlocks = {};
    for i = 1:numel(observeBlocks)
        block = observeBlocks{i};
        try
            handles = get_param(block, 'PortHandles');
        catch
            continue;
        end
        for p = 1:numel(handles.Inport)
            line = get_param(handles.Inport(p), 'Line');
            if isequal(line, -1)
                continue;
            end
            variable = matlab.lang.makeValidName(sprintf('probe_%03d_%03d_%03d', scenarioIndex, i, p));
            try
                add_to_workspace_probe(block, line, variable);
                probeSpecs(end + 1).path = block; %#ok<AGROW>
                probeSpecs(end).port = p;
                probeSpecs(end).variable = variable;
                probeBlocks{end + 1} = [get_param(block, 'Parent') '/' ... %#ok<AGROW>
                    matlab.lang.makeValidName(['CodexProbe_' variable])];
            catch
            end
        end
    end
end

function observations = collect_block_observations(out, probeSpecs)
    observations = struct('path', {}, 'port', {}, 'value', {}, 'present', {});
    for i = 1:numel(probeSpecs)
        value = [];
        try
            ts = out.get(probeSpecs(i).variable);
            value = sample_final_value(ts);
        catch
        end
        observations(end + 1).path = probeSpecs(i).path; %#ok<AGROW>
        observations(end).port = probeSpecs(i).port;
        observations(end).value = value;
        observations(end).present = ~isempty(value);
    end
end

function outputs = collect_root_outputs(out, outputNames)
    outputs = struct();
    for k = 1:numel(outputNames)
        try
            ts = out.get(outputNames{k});
            value = sample_final_value(ts);
            outputs.(outputNames{k}) = value;
        catch
        end
    end
end

function value = sample_final_value(ts)
    value = [];
    data = ts.Data;
    if isempty(data)
        return;
    end
    data = squeeze(data);
    if size(data, 1) > 1
        data = data(end, :);
    end
    data = data(~isnan(data));
    if isempty(data)
        return;
    end
    value = data(end);
end

function restore = snapshot_parameters(overrides)
    restore = struct();
    names = fieldnames(overrides);
    for i = 1:numel(names)
        name = names{i};
        try
            obj = evalin('base', name);
            if isprop(obj, 'Value')
                restore.(name) = obj.Value;
            else
                restore.(name) = obj;
            end
        catch
        end
    end
end

function restore_parameters(restore)
    names = fieldnames(restore);
    for i = 1:numel(names)
        name = names{i};
        try
            obj = evalin('base', name);
            if isprop(obj, 'Value')
                obj.Value = restore.(name);
                assignin('base', name, obj);
            else
                assignin('base', name, restore.(name));
            end
        catch
        end
    end
end

function remove_probe_blocks(probeBlocks)
    for i = 1:numel(probeBlocks)
        try
            delete_block(probeBlocks{i});
        catch
        end
    end
end

function value = normalize_input_value(value, width)
    value = double(value);
    value = value(:)';
    if numel(value) == width
        return;
    end
    if numel(value) == 1
        value = repmat(value, 1, width);
    end
end

function apply_parameter_overrides(overrides)
    names = fieldnames(overrides);
    for i = 1:numel(names)
        name = names{i};
        value = overrides.(name);
        try
            obj = evalin('base', name);
            if isprop(obj, 'Value')
                currentValue = obj.Value;
                dataType = '';
                if isprop(obj, 'DataType')
                    dataType = obj.DataType;
                end
                value = cast_parameter_override_for_simulink_ut(name, value, currentValue, dataType);
                obj.Value = value;
                assignin('base', name, obj);
            else
                value = cast_parameter_override_for_simulink_ut(name, value, obj, '');
                assignin('base', name, value);
            end
        catch
            assignin('base', name, value);
        end
    end
end

function arr = normalize_struct_array(value)
    if isstruct(value)
        arr = value;
    elseif iscell(value)
        arr = [value{:}];
    else
        arr = struct([]);
    end
end

function value = ensure_struct(parent, fieldName)
    if isfield(parent, fieldName) && isstruct(parent.(fieldName))
        value = parent.(fieldName);
    else
        value = struct();
    end
end

function filePath = resolve_workspace_file(rootDir, fileName)
    filePath = char(string(fileName));
    if ~isfile(filePath)
        filePath = fullfile(rootDir, filePath);
    end
end

function load_mat_to_base(matPath)
    if ~exist(matPath, 'file')
        return;
    end
    try
        vars = whos('-file', matPath);
        names = {vars.name};
        for i = 1:numel(names)
            try
                if ~evalin('base', ['exist(''' names{i} ''', ''var'')'])
                    data = load(matPath, names{i});
                    assignin('base', names{i}, data.(names{i}));
                end
            catch
            end
        end
    catch
    end
end

function add_to_workspace_probe(targetBlock, line, variableName)
    parentSystem = get_param(targetBlock, 'Parent');
    srcPort = get_param(line, 'SrcPortHandle');
    blockName = matlab.lang.makeValidName(['CodexProbe_' variableName]);
    probeBlock = [parentSystem '/' blockName];
    suffix = 1;
    while getSimulinkBlockHandle(probeBlock) ~= -1
        blockName = matlab.lang.makeValidName(sprintf('CodexProbe_%s_%d', variableName, suffix));
        probeBlock = [parentSystem '/' blockName];
        suffix = suffix + 1;
    end
    try
        add_block('simulink/Sinks/To Workspace', probeBlock, ...
            'VariableName', variableName, ...
            'SaveFormat', 'Timeseries', ...
            'Position', [30 + 15 * suffix, 30 + 15 * suffix, 140 + 15 * suffix, 60 + 15 * suffix]);
    catch ME
        if contains(ME.message, '链接库模块') || contains(lower(ME.message), 'library') || contains(lower(ME.message), 'locked')
            deactivate_link(parentSystem);
            add_block('simulink/Sinks/To Workspace', probeBlock, ...
                'VariableName', variableName, ...
                'SaveFormat', 'Timeseries', ...
                'Position', [30 + 15 * suffix, 30 + 15 * suffix, 140 + 15 * suffix, 60 + 15 * suffix]);
        else
            rethrow(ME);
        end
    end
    dstHandles = get_param(probeBlock, 'PortHandles');
    add_line(parentSystem, srcPort, dstHandles.Inport(1), 'autorouting', 'on');
end

function deactivate_link(systemPath)
    current = systemPath;
    while ~isempty(current)
        try
            status = get_param(current, 'LinkStatus');
            if ~strcmpi(status, 'none')
                set_param(current, 'LinkStatus', 'inactive');
                return;
            end
        catch
        end
        parent = get_param(current, 'Parent');
        if isempty(parent) || strcmp(parent, current)
            return;
        end
        current = parent;
    end
end

function write_json_file(pathName, data)
    out = char(string(pathName));
    folder = fileparts(out);
    if ~exist(folder, 'dir')
        mkdir(folder);
    end
    fid = fopen(out, 'w');
    if fid < 0
        error('probe_block_inputs:open', 'cannot open %s for writing', out);
    end
    fprintf(fid, '%s', jsonencode(data, 'PrettyPrint', true));
    fclose(fid);
    fprintf('Wrote %s\n', out);
end
