param(
  [string]$InstallDir = "C:\SoftwareDocWorker",
  [string]$ApiHost = "0.0.0.0",
  [int]$ApiPort = 8642,
  [int]$NoKeyInternalPort = 8643,
  [string]$AllowedRemoteAddress = "10.36.77.221",
  [string]$TaskName = "SoftwareDocHermesOpenApiServer",
  [string]$ApiKey = "",
  [switch]$AllowNoApiKey,
  [switch]$NoFirewall,
  [switch]$NoScheduledTask
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Assert-Administrator {
  $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
  $principal = [Security.Principal.WindowsPrincipal]::new($identity)
  if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Please run this script from an elevated PowerShell window."
  }
}

function Import-EnvFile {
  param(
    [string]$Path,
    [switch]$Required
  )
  if (-not (Test-Path -LiteralPath $Path)) {
    if ($Required) {
      throw "Environment file not found: $Path"
    }
    return
  }
  foreach ($line in Get-Content -LiteralPath $Path -Encoding UTF8) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith("#")) {
      continue
    }
    $index = $trimmed.IndexOf("=")
    if ($index -le 0) {
      continue
    }
    $key = $trimmed.Substring(0, $index).Trim()
    $value = $trimmed.Substring($index + 1).Trim().Trim('"').Trim("'")
    [Environment]::SetEnvironmentVariable($key, $value, "Process")
  }
}

function Write-EnvFile {
  param(
    [string]$Path,
    [hashtable]$Values
  )
  $lines = @(
    "# Hermes OpenAI-compatible API Server environment",
    "# Generated by Enable-HermesOpenApiServer.ps1"
  )
  foreach ($key in ($Values.Keys | Sort-Object)) {
    $value = [string]$Values[$key]
    $lines += "$key=$value"
  }
  $parent = Split-Path -Parent $Path
  New-Item -ItemType Directory -Force -Path $parent | Out-Null
  $lines | Set-Content -LiteralPath $Path -Encoding UTF8
}

function Get-RandomApiKey {
  $bytes = New-Object byte[] 32
  $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($bytes)
  } finally {
    $rng.Dispose()
  }
  return "hsk_" + [Convert]::ToBase64String($bytes).Replace("+", "-").Replace("/", "_").TrimEnd("=")
}

function Resolve-HermesCommand {
  param([string]$Root)
  $candidates = @()
  if ($env:HERMES_COMMAND) {
    $candidates += $env:HERMES_COMMAND
  }
  $candidates += @(
    (Join-Path $Root "runtime\hermes-agent\hermes.cmd"),
    (Join-Path $Root "runtime\hermes\hermes.cmd"),
    (Join-Path $Root "hermes.cmd")
  )
  foreach ($candidate in $candidates) {
    if ($candidate -and (Test-Path -LiteralPath $candidate)) {
      return (Resolve-Path -LiteralPath $candidate).Path
    }
  }
  throw "Hermes command not found. Check HERMES_COMMAND in $Root\software-doc-worker.env."
}

function Resolve-HermesHome {
  param(
    [string]$Root,
    [string]$HermesCommand
  )
  if ($env:HERMES_HOME) {
    return $env:HERMES_HOME
  }
  $homeFromCmd = $null
  if ($HermesCommand.EndsWith(".cmd", [StringComparison]::OrdinalIgnoreCase)) {
    foreach ($line in Get-Content -LiteralPath $HermesCommand -Encoding ASCII) {
      if ($line -match '^\s*set\s+HERMES_HOME=(.+?)\s*$') {
        $homeFromCmd = $Matches[1].Trim('"')
        break
      }
    }
  }
  if ($homeFromCmd) {
    return $homeFromCmd
  }
  return (Join-Path $Root "runtime\hermes-home")
}

function Resolve-HermesPython {
  param([string]$HermesCommand)
  $hermesRoot = Split-Path -Parent $HermesCommand
  $candidates = @(
    (Join-Path $hermesRoot "python\python.exe"),
    (Join-Path $hermesRoot "venv\Scripts\python.exe")
  )
  foreach ($candidate in $candidates) {
    if (Test-Path -LiteralPath $candidate) {
      return (Resolve-Path -LiteralPath $candidate).Path
    }
  }
  throw "Cannot locate Hermes Python runtime under $hermesRoot."
}

function Ensure-Pip {
  param([string]$PythonExe)
  & $PythonExe -m pip --version *> $null
  if ($LASTEXITCODE -eq 0) {
    return
  }

  $getPip = Join-Path ([IO.Path]::GetTempPath()) ("get-pip-" + [guid]::NewGuid().ToString("N") + ".py")
  Write-Host "pip not found in Hermes Python runtime; downloading get-pip.py..."
  Invoke-WebRequest -Uri "https://bootstrap.pypa.io/get-pip.py" -OutFile $getPip
  try {
    & $PythonExe $getPip --no-warn-script-location
    if ($LASTEXITCODE -ne 0) {
      throw "get-pip.py failed with exit code $LASTEXITCODE"
    }
  } finally {
    Remove-Item -LiteralPath $getPip -Force -ErrorAction SilentlyContinue
  }
}

function Ensure-PythonPackage {
  param(
    [string]$PythonExe,
    [string]$ImportName,
    [string]$PackageName
  )
  & $PythonExe -c "import $ImportName" *> $null
  if ($LASTEXITCODE -eq 0) {
    Write-Host "Python package already available: $ImportName"
    return
  }
  Write-Host "Installing Python package: $PackageName"
  & $PythonExe -m pip install --disable-pip-version-check --upgrade $PackageName
  if ($LASTEXITCODE -ne 0) {
    throw "Failed to install Python package: $PackageName"
  }
}

function Update-HermesConfig {
  param(
    [string]$PythonExe,
    [string]$HermesHome,
    [string]$McpServerCommand
  )
  New-Item -ItemType Directory -Force -Path $HermesHome | Out-Null
  $configPath = Join-Path $HermesHome "config.yaml"
  $mergeScript = @'
import sys
import os
from pathlib import Path
import yaml

config_path = Path(sys.argv[1])
mcp_command = sys.argv[2]

if config_path.exists():
    data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
else:
    data = {}
if not isinstance(data, dict):
    data = {}

servers = data.setdefault("mcp_servers", {})
server_env = {}
for key in [
    "MATLAB_EXECUTABLE",
    "MATLAB_ROOT",
    "MATLAB_MCP_TMPDIR",
    "SOFTWARE_DOC_RUNTIME_PATHS",
    "PATH",
]:
    value = os.environ.get(key)
    if value:
        server_env[key] = value
tmp_dir = os.environ.get("MATLAB_MCP_TMPDIR") or os.environ.get("TEMP") or os.environ.get("TMP")
if tmp_dir:
    server_env["TMPDIR"] = tmp_dir
    server_env["TMP"] = tmp_dir
    server_env["TEMP"] = tmp_dir
server_env["NO_COLOR"] = "1"

servers["matlab_satk"] = {
    "command": mcp_command,
    "args": [],
    "env": server_env,
    "enabled": True,
    "timeout": 600,
    "connect_timeout": 120,
    "supports_parallel_tool_calls": False,
    "tools": {
        "resources": True,
        "prompts": True,
    },
}

platform_toolsets = data.setdefault("platform_toolsets", {})
existing = platform_toolsets.get("api_server") or []
if not isinstance(existing, list):
    existing = []
wanted = ["hermes-api-server", "mcp-matlab_satk"]
merged = []
for name in [*wanted, *existing]:
    if name and name not in merged:
        merged.append(name)
platform_toolsets["api_server"] = merged

provider = (
    os.environ.get("HERMES_LLM_PROVIDER")
    or os.environ.get("HERMES_INFERENCE_PROVIDER")
    or ""
).strip().lower()
provider_aliases = {
    "glm": "zai",
    "zhipu": "zai",
}
provider = provider_aliases.get(provider, provider)
model_name = (
    os.environ.get("OPENAI_MODEL")
    or os.environ.get("API_SERVER_MODEL_NAME")
    or ""
).strip()
if provider or model_name:
    model_cfg = data.setdefault("model", {})
    if provider:
        model_cfg["provider"] = provider
    if model_name:
        model_cfg["default"] = model_name
    model_cfg.setdefault("base_url", "")
    model_cfg.setdefault("api_mode", "chat_completions")

config_path.write_text(
    yaml.safe_dump(data, sort_keys=False, allow_unicode=True),
    encoding="utf-8",
)
'@
  $tmp = Join-Path ([IO.Path]::GetTempPath()) ("merge-hermes-config-" + [guid]::NewGuid().ToString("N") + ".py")
  Set-Content -LiteralPath $tmp -Value $mergeScript -Encoding UTF8
  try {
    & $PythonExe $tmp $configPath $McpServerCommand
    if ($LASTEXITCODE -ne 0) {
      throw "Failed to update Hermes config: $configPath"
    }
  } finally {
    Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue
  }
}

function Write-RunnerScript {
  param([string]$Path)
  $content = @'
param(
  [string]$InstallDir = "C:\SoftwareDocWorker"
)

$ErrorActionPreference = "Stop"

function Import-EnvFile {
  param(
    [string]$Path,
    [switch]$Required
  )
  if (-not (Test-Path -LiteralPath $Path)) {
    if ($Required) {
      throw "Environment file not found: $Path"
    }
    return
  }
  foreach ($line in Get-Content -LiteralPath $Path -Encoding UTF8) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith("#")) {
      continue
    }
    $index = $trimmed.IndexOf("=")
    if ($index -le 0) {
      continue
    }
    $key = $trimmed.Substring(0, $index).Trim()
    $value = $trimmed.Substring($index + 1).Trim().Trim('"').Trim("'")
    [Environment]::SetEnvironmentVariable($key, $value, "Process")
  }
}

$envFile = Join-Path $InstallDir "software-doc-worker.env"
$llmEnvFile = Join-Path $InstallDir "config\hermes-llm.active.env"
$apiEnvFile = Join-Path $InstallDir "config\hermes-api-server.env"
$appDir = Join-Path $InstallDir "app"
$logDir = Join-Path $InstallDir "logs"
New-Item -ItemType Directory -Force -Path $logDir | Out-Null
$logPath = Join-Path $logDir ("hermes-openapi-{0}.log" -f (Get-Date -Format "yyyyMMdd"))
Start-Transcript -Path $logPath -Append | Out-Null

try {
  Import-EnvFile -Path $envFile -Required
  Import-EnvFile -Path $llmEnvFile
  Import-EnvFile -Path $apiEnvFile -Required

  if (-not $env:HERMES_INFERENCE_PROVIDER -and $env:HERMES_LLM_PROVIDER) {
    $env:HERMES_INFERENCE_PROVIDER = $env:HERMES_LLM_PROVIDER
  }
  if ($env:HERMES_LLM_API_KEY_ENV -and $env:HERMES_INFERENCE_PROVIDER) {
    $sourceKeyName = $env:HERMES_LLM_API_KEY_ENV.Trim()
    $sourceKeyValue = [Environment]::GetEnvironmentVariable($sourceKeyName, "Process")
    if (-not $sourceKeyValue) {
      $sourceKeyValue = $env:OPENAI_API_KEY
    }
    switch ($env:HERMES_INFERENCE_PROVIDER.Trim().ToLowerInvariant()) {
      "deepseek" {
        if (-not $env:DEEPSEEK_API_KEY -and $sourceKeyValue) {
          $env:DEEPSEEK_API_KEY = $sourceKeyValue
        }
      }
      { $_ -in @("glm", "zai", "zhipu") } {
        if (-not $env:GLM_API_KEY -and $sourceKeyValue) {
          $env:GLM_API_KEY = $sourceKeyValue
        }
        if (-not $env:ZAI_API_KEY -and $sourceKeyValue) {
          $env:ZAI_API_KEY = $sourceKeyValue
        }
      }
      "kimi-coding" {
        if (-not $env:KIMI_API_KEY -and $sourceKeyValue) {
          $env:KIMI_API_KEY = $sourceKeyValue
        }
      }
    }
  }

  if ($env:SOFTWARE_DOC_RUNTIME_PATHS) {
    foreach ($runtimePath in ($env:SOFTWARE_DOC_RUNTIME_PATHS -split ";")) {
      if ($runtimePath -and (Test-Path -LiteralPath $runtimePath)) {
        $env:Path = "$runtimePath;$env:Path"
      }
    }
  }

  if (-not $env:HERMES_COMMAND -or -not (Test-Path -LiteralPath $env:HERMES_COMMAND)) {
    throw "HERMES_COMMAND is missing or invalid."
  }

  New-Item -ItemType Directory -Force -Path `
    (Join-Path $InstallDir "tmp"), `
    (Join-Path $InstallDir "tmp\matlab"), `
    (Join-Path $InstallDir "tmp\hermes-uploads") | Out-Null

  if (Test-Path -LiteralPath $appDir) {
    Set-Location $appDir
  }

  & $env:HERMES_COMMAND gateway
  exit $LASTEXITCODE
} finally {
  Stop-Transcript | Out-Null
}
'@
  $parent = Split-Path -Parent $Path
  New-Item -ItemType Directory -Force -Path $parent | Out-Null
  Set-Content -LiteralPath $Path -Value $content -Encoding UTF8
}

function Ensure-FirewallRule {
  param(
    [int]$Port,
    [string]$RemoteAddress
  )
  if ($NoFirewall) {
    return
  }
  $displayName = "SoftwareDoc Hermes OpenAI API Server $Port"
  $existing = Get-NetFirewallRule -DisplayName $displayName -ErrorAction SilentlyContinue
  if ($existing) {
    Remove-NetFirewallRule -DisplayName $displayName
  }
  $remote = if ($RemoteAddress -and $RemoteAddress -ne "Any") { $RemoteAddress } else { "Any" }
  New-NetFirewallRule `
    -DisplayName $displayName `
    -Direction Inbound `
    -Action Allow `
    -Protocol TCP `
    -LocalPort $Port `
    -RemoteAddress $remote | Out-Null
}

function Ensure-PortProxy {
  param(
    [int]$PublicPort,
    [int]$InternalPort
  )
  Start-Service iphlpsvc -ErrorAction SilentlyContinue
  netsh interface portproxy delete v4tov4 listenaddress=0.0.0.0 listenport=$PublicPort *> $null
  netsh interface portproxy delete v4tov4 listenaddress=127.0.0.1 listenport=$PublicPort *> $null
  netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=$PublicPort connectaddress=127.0.0.1 connectport=$InternalPort | Out-Null
}

function Register-OpenApiTask {
  param(
    [string]$Name,
    [string]$RunnerPath,
    [string]$Root
  )
  if ($NoScheduledTask) {
    return
  }
  $existing = Get-ScheduledTask -TaskName $Name -ErrorAction SilentlyContinue
  if ($existing) {
    Stop-ScheduledTask -TaskName $Name -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
  }
  $arguments = @(
    "-NoProfile",
    "-ExecutionPolicy", "Bypass",
    "-File", "`"$RunnerPath`"",
    "-InstallDir", "`"$Root`""
  ) -join " "
  $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument $arguments -WorkingDirectory $Root
  $trigger = New-ScheduledTaskTrigger -AtLogOn
  $principal = New-ScheduledTaskPrincipal `
    -UserId ([Security.Principal.WindowsIdentity]::GetCurrent().Name) `
    -LogonType Interactive `
    -RunLevel Highest
  $settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1)
  Register-ScheduledTask -TaskName $Name -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Force | Out-Null
  Start-ScheduledTask -TaskName $Name
}

function Wait-ApiServer {
  param(
    [int]$Port,
    [string]$BearerToken
  )
  $healthUri = "http://127.0.0.1:$Port/health"
  $modelsUri = "http://127.0.0.1:$Port/v1/models"
  $headers = @{}
  if ($BearerToken) {
    $headers.Authorization = "Bearer $BearerToken"
  }
  for ($i = 0; $i -lt 30; $i++) {
    try {
      Invoke-RestMethod -Uri $healthUri -TimeoutSec 3 | Out-Null
      if ($headers.Count) {
        Invoke-RestMethod -Uri $modelsUri -Headers $headers -TimeoutSec 3 | Out-Null
      } else {
        Invoke-RestMethod -Uri $modelsUri -TimeoutSec 3 | Out-Null
      }
      return
    } catch {
      Start-Sleep -Seconds 2
    }
  }
  throw "Hermes API Server did not become healthy on port $Port. Check $InstallDir\logs\hermes-openapi-*.log."
}

Assert-Administrator

$envFile = Join-Path $InstallDir "software-doc-worker.env"
$llmEnvFile = Join-Path $InstallDir "config\hermes-llm.active.env"
Import-EnvFile -Path $envFile -Required
Import-EnvFile -Path $llmEnvFile

if ($env:SOFTWARE_DOC_RUNTIME_PATHS) {
  foreach ($runtimePath in ($env:SOFTWARE_DOC_RUNTIME_PATHS -split ";")) {
    if ($runtimePath -and (Test-Path -LiteralPath $runtimePath)) {
      $env:Path = "$runtimePath;$env:Path"
    }
  }
}

$hermesCommand = Resolve-HermesCommand -Root $InstallDir
$hermesHome = Resolve-HermesHome -Root $InstallDir -HermesCommand $hermesCommand
$pythonExe = Resolve-HermesPython -HermesCommand $hermesCommand

if (-not $env:MATLAB_MCP_SERVER_COMMAND -or -not (Test-Path -LiteralPath $env:MATLAB_MCP_SERVER_COMMAND)) {
  $fallbackMcp = Join-Path $InstallDir "app\tools\matlab-mcp-core-server.exe"
  if (Test-Path -LiteralPath $fallbackMcp) {
    $env:MATLAB_MCP_SERVER_COMMAND = $fallbackMcp
  } else {
    throw "MATLAB_MCP_SERVER_COMMAND is missing or invalid."
  }
}
$mcpServerCommand = (Resolve-Path -LiteralPath $env:MATLAB_MCP_SERVER_COMMAND).Path

if ($AllowNoApiKey) {
  $ApiKey = ""
} elseif (-not $ApiKey) {
  $apiEnvFileExisting = Join-Path $InstallDir "config\hermes-api-server.env"
  if (Test-Path -LiteralPath $apiEnvFileExisting) {
    Import-EnvFile -Path $apiEnvFileExisting
  }
  if ($env:API_SERVER_KEY) {
    $ApiKey = $env:API_SERVER_KEY
  } else {
    $ApiKey = Get-RandomApiKey
  }
}

$modelName = if ($env:OPENAI_MODEL) { $env:OPENAI_MODEL } else { "hermes-windows-agent" }
$apiEnvPath = Join-Path $InstallDir "config\hermes-api-server.env"
$effectiveApiHost = $ApiHost
$effectiveApiPort = $ApiPort
if ($AllowNoApiKey -and $ApiHost -in @("0.0.0.0", "::", "*")) {
  $effectiveApiHost = "127.0.0.1"
  $effectiveApiPort = $NoKeyInternalPort
  Ensure-PortProxy -PublicPort $ApiPort -InternalPort $effectiveApiPort
}
Write-EnvFile -Path $apiEnvPath -Values @{
  "API_SERVER_ENABLED" = "true"
  "API_SERVER_HOST" = $effectiveApiHost
  "API_SERVER_PORT" = [string]$effectiveApiPort
  "API_SERVER_KEY" = $ApiKey
  "API_SERVER_MODEL_NAME" = $modelName
}

Write-Host "Hermes command: $hermesCommand"
Write-Host "Hermes home: $hermesHome"
Write-Host "Hermes Python: $pythonExe"
Write-Host "MATLAB/SATK MCP command: $mcpServerCommand"
Write-Host "API server env file: $apiEnvPath"

Ensure-Pip -PythonExe $pythonExe
Ensure-PythonPackage -PythonExe $pythonExe -ImportName "aiohttp" -PackageName "aiohttp"
Ensure-PythonPackage -PythonExe $pythonExe -ImportName "yaml" -PackageName "PyYAML"
Update-HermesConfig -PythonExe $pythonExe -HermesHome $hermesHome -McpServerCommand $mcpServerCommand

$runnerPath = Join-Path $InstallDir "scripts\run-hermes-openai-api-server.ps1"
Write-RunnerScript -Path $runnerPath
Ensure-FirewallRule -Port $ApiPort -RemoteAddress $AllowedRemoteAddress
Register-OpenApiTask -Name $TaskName -RunnerPath $runnerPath -Root $InstallDir

if (-not $NoScheduledTask) {
  Wait-ApiServer -Port $effectiveApiPort -BearerToken $ApiKey
  if ($AllowNoApiKey -and $effectiveApiPort -ne $ApiPort) {
    Wait-ApiServer -Port $ApiPort -BearerToken ""
  }
}

Write-Host ""
Write-Host "Hermes OpenAI-compatible API Server is ready."
Write-Host "Local health: http://127.0.0.1:$effectiveApiPort/health"
Write-Host "Linux URL: http://<windows-vm-host>:$ApiPort/v1"
if ($AllowNoApiKey) {
  Write-Host "API key authentication: disabled"
  if ($effectiveApiPort -ne $ApiPort) {
    Write-Host "No-key mode uses Windows portproxy: 0.0.0.0:$ApiPort -> 127.0.0.1:$effectiveApiPort"
  }
} else {
  Write-Host "API key is stored in: $apiEnvPath"
}
Write-Host "Task name: $TaskName"
