param(
  [ValidateSet("menu", "list", "show", "set", "test", "init")]
  [string]$Action = "menu",
  [string]$ProfileId = "",
  [string]$InstallDir = "C:\SoftwareDocWorker",
  [string]$DeepSeekApiKey = "",
  [string]$ZhipuApiKey = "",
  [string]$ApiKey = "",
  [switch]$NoRestart,
  [switch]$NoTest
)

$ErrorActionPreference = "Stop"

function Get-ConfigDir {
  param([string]$Root)
  return Join-Path $Root "config"
}

function Get-BundledProfilesPath {
  param([string]$Root)
  $candidates = @(
    (Join-Path $Root "app\scripts\hermes-llm-profiles.json"),
    (Join-Path $PSScriptRoot "hermes-llm-profiles.json")
  )
  foreach ($candidate in $candidates) {
    if (Test-Path -LiteralPath $candidate) {
      return $candidate
    }
  }
  throw "Cannot find bundled Hermes LLM profiles."
}

function Sync-ProfilesFile {
  param([string]$Root)
  $configDir = Get-ConfigDir -Root $Root
  New-Item -ItemType Directory -Force -Path $configDir | Out-Null
  $source = Get-BundledProfilesPath -Root $Root
  $target = Join-Path $configDir "hermes-llm-profiles.json"
  Copy-Item -LiteralPath $source -Destination $target -Force
  return $target
}

function Read-EnvFile {
  param([string]$Path)
  $values = [ordered]@{}
  if (-not (Test-Path -LiteralPath $Path)) {
    return $values
  }
  foreach ($line in Get-Content -LiteralPath $Path -Encoding UTF8) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith("#")) {
      continue
    }
    $index = $trimmed.IndexOf("=")
    if ($index -le 0) {
      continue
    }
    $key = $trimmed.Substring(0, $index).Trim()
    $value = $trimmed.Substring($index + 1).Trim().Trim('"').Trim("'")
    $values[$key] = $value
  }
  return $values
}

function Write-EnvFile {
  param(
    [string]$Path,
    [System.Collections.IDictionary]$Values,
    [string[]]$Header = @()
  )
  $parent = Split-Path -Parent $Path
  New-Item -ItemType Directory -Force -Path $parent | Out-Null
  $lines = @()
  foreach ($line in $Header) {
    $lines += "# $line"
  }
  foreach ($key in $Values.Keys) {
    $lines += "$key=$($Values[$key])"
  }
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllLines($Path, $lines, $utf8NoBom)
}

function Protect-SecretsFile {
  param([string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) {
    return
  }
  try {
    $currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
    & icacls.exe $Path /inheritance:r /grant:r "${currentUser}:(M)" "Administrators:(F)" "SYSTEM:(F)" | Out-Null
  } catch {
    Write-Warning "Unable to tighten ACL for secrets file: $Path"
  }
}

function Load-Profiles {
  param([string]$Path)
  $document = Get-Content -Raw -Encoding UTF8 -LiteralPath $Path | ConvertFrom-Json
  foreach ($profile in @($document.profiles)) {
    if (-not $profile.apiMode) {
      $profile | Add-Member -NotePropertyName apiMode -NotePropertyValue "chat_completions"
    }
  }
  return $document
}

function Find-Profile {
  param(
    [object]$ProfilesDoc,
    [string]$Id
  )
  $profile = @($ProfilesDoc.profiles) | Where-Object { $_.id -eq $Id } | Select-Object -First 1
  if (-not $profile) {
    throw "Unknown Hermes LLM profile: $Id"
  }
  return $profile
}

function Save-ProvidedSecrets {
  param(
    [string]$SecretsPath,
    [string]$DeepSeek,
    [string]$Zhipu,
    [string]$GenericApiKey,
    [string]$GenericApiKeyName
  )
  $secrets = Read-EnvFile -Path $SecretsPath
  if ($DeepSeek) {
    $secrets["DEEPSEEK_API_KEY"] = $DeepSeek
  }
  if ($Zhipu) {
    $secrets["ZHIPU_API_KEY"] = $Zhipu
  }
  if ($GenericApiKey -and $GenericApiKeyName) {
    $secrets[$GenericApiKeyName] = $GenericApiKey
  }
  if ($DeepSeek -or $Zhipu -or ($GenericApiKey -and $GenericApiKeyName)) {
    Write-EnvFile -Path $SecretsPath -Values $secrets -Header @(
      "Hermes LLM API keys. Do not commit or copy into the app source tree.",
      "Generated by Switch-HermesLlmProfile.ps1."
    )
    Protect-SecretsFile -Path $SecretsPath
  }
}

function Test-PlaceholderApiKey {
  param([string]$Value)
  $trimmed = [string]$Value
  $trimmed = $trimmed.Trim()
  if (-not $trimmed) {
    return $false
  }
  if ($trimmed.StartsWith("<") -or $trimmed.EndsWith(">")) {
    return $true
  }
  return $trimmed -match "(?i)(deepseek key|glm key|api key|your key|placeholder)"
}

function Resolve-HermesPython {
  param([string]$Root)
  if ($env:HERMES_PYTHON_EXE -and (Test-Path -LiteralPath $env:HERMES_PYTHON_EXE)) {
    return $env:HERMES_PYTHON_EXE
  }
  $candidates = @(
    (Join-Path $Root "runtime\hermes-agent\python\python.exe"),
    (Join-Path $Root "runtime\hermes-agent\venv\Scripts\python.exe"),
    (Join-Path $Root "runtime\hermes\python\python.exe"),
    (Join-Path $Root "runtime\hermes\venv\Scripts\python.exe")
  )
  foreach ($candidate in $candidates) {
    if (Test-Path -LiteralPath $candidate) {
      return $candidate
    }
  }
  throw "Hermes Python runtime was not found under $Root\runtime."
}

function Update-HermesConfig {
  param(
    [object]$Profile,
    [string]$Root
  )
  $pythonExe = Resolve-HermesPython -Root $Root
  $hermesHome = Join-Path $Root "runtime\hermes-home"
  New-Item -ItemType Directory -Force -Path $hermesHome | Out-Null
  $configPath = Join-Path $hermesHome "config.yaml"
  $mergeScript = @'
import os
import sys
import tempfile
from pathlib import Path
import yaml

config_path = Path(sys.argv[1])
profile_id, provider, base_url, model_name, key_env, api_mode, reasoning_effort = sys.argv[2:]
provider_name = f"custom:{profile_id}" if provider == "custom" else provider

if config_path.exists():
    data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
else:
    data = {}
if not isinstance(data, dict):
    raise SystemExit("Hermes config.yaml must contain a YAML mapping")

if provider == "custom":
    providers = data.setdefault("custom_providers", [])
    if not isinstance(providers, list):
        raise SystemExit("Hermes custom_providers must be a YAML list")
    entry = {
        "name": profile_id,
        "base_url": base_url,
        "key_env": key_env,
        "api_mode": api_mode,
    }
    for index, candidate in enumerate(providers):
        if isinstance(candidate, dict) and candidate.get("name") == profile_id:
            providers[index] = {**candidate, **entry}
            break
    else:
        providers.append(entry)

model = data.setdefault("model", {})
if not isinstance(model, dict):
    raise SystemExit("Hermes model config must be a YAML mapping")
model.update({"provider": provider_name, "default": model_name, "api_mode": api_mode})

delegation = data.setdefault("delegation", {})
if not isinstance(delegation, dict):
    raise SystemExit("Hermes delegation config must be a YAML mapping")
delegation.update({"provider": provider_name, "model": model_name, "api_mode": api_mode})

agent = data.setdefault("agent", {})
if not isinstance(agent, dict):
    raise SystemExit("Hermes agent config must be a YAML mapping")
if reasoning_effort:
    agent["reasoning_effort"] = reasoning_effort

config_path.parent.mkdir(parents=True, exist_ok=True)
fd, temporary_name = tempfile.mkstemp(prefix="config-", suffix=".yaml.tmp", dir=config_path.parent)
try:
    with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as output:
        yaml.safe_dump(data, output, sort_keys=False, allow_unicode=True)
        output.flush()
        os.fsync(output.fileno())
    os.replace(temporary_name, config_path)
except BaseException:
    try:
        os.unlink(temporary_name)
    except FileNotFoundError:
        pass
    raise
'@
  $temporaryScript = Join-Path ([IO.Path]::GetTempPath()) ("merge-hermes-llm-config-" + [guid]::NewGuid().ToString("N") + ".py")
  [IO.File]::WriteAllText($temporaryScript, $mergeScript, [Text.UTF8Encoding]::new($false))
  try {
    & $pythonExe $temporaryScript $configPath $Profile.id $Profile.provider $Profile.baseURL $Profile.model $Profile.apiKeyEnv $Profile.apiMode $Profile.reasoningEffort
    if ($LASTEXITCODE -ne 0) {
      throw "Failed to update Hermes config: $configPath"
    }
  } finally {
    Remove-Item -LiteralPath $temporaryScript -Force -ErrorAction SilentlyContinue
  }
}

function Write-ActiveProfile {
  param(
    [object]$Profile,
    [string]$ActivePath
  )
  $inferenceProvider = if ($Profile.provider -eq "custom") { "custom:$($Profile.id)" } else { $Profile.provider }
  $values = [ordered]@{
    "HERMES_LLM_PROFILE" = $Profile.id
    "HERMES_LLM_PROVIDER" = $Profile.provider
    "HERMES_INFERENCE_PROVIDER" = $inferenceProvider
    "HERMES_LLM_API_KEY_ENV" = $Profile.apiKeyEnv
    "HERMES_LLM_API_MODE" = $Profile.apiMode
    "HERMES_REASONING_EFFORT" = $Profile.reasoningEffort
    "OPENAI_BASE_URL" = $Profile.baseURL
    "OPENAI_MODEL" = $Profile.model
  }
  Write-EnvFile -Path $ActivePath -Values $values -Header @(
    "Active Hermes LLM profile. This file contains no secrets.",
    "Generated by Switch-HermesLlmProfile.ps1."
  )
}

function Restart-HermesTask {
  $serviceName = "SoftwareDocHermesAgent"
  $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
  if ($service) {
    if ($service.Status -eq "Running") {
      Restart-Service -Name $serviceName -Force
    } else {
      Start-Service -Name $serviceName
    }
    (Get-Service -Name $serviceName).WaitForStatus("Running", [TimeSpan]::FromSeconds(30))
    Start-Sleep -Seconds 3
    return
  }

  $taskName = "SoftwareDocHermesAgent"
  $task = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
  if (-not $task) {
    Write-Warning "Hermes service or scheduled task not found: $taskName"
    return
  }
  if ($task.State -eq "Running") {
    Stop-ScheduledTask -TaskName $taskName
    Start-Sleep -Seconds 2
  }
  Start-ScheduledTask -TaskName $taskName
  Start-Sleep -Seconds 3
}
function Test-HermesHealth {
  param([string]$WorkerEnvPath)
  $workerEnv = Read-EnvFile -Path $WorkerEnvPath
  $port = $workerEnv["HERMES_PORT"]
  if (-not $port) {
    $port = "3101"
  }
  $headers = @{}
  if ($workerEnv["HERMES_AUTH_TOKEN"]) {
    $headers["Authorization"] = "Bearer $($workerEnv["HERMES_AUTH_TOKEN"])"
  }
  $health = Invoke-RestMethod -Method Get -Uri "http://127.0.0.1:$port/api/health" -TimeoutSec 10
  Write-Host "Hermes health: ok=$($health.ok), port=$($health.port)"
  try {
    $debug = Invoke-RestMethod -Method Get -Uri "http://127.0.0.1:$port/api/debug/llm" -Headers $headers -TimeoutSec 10
    Write-Host "Hermes LLM: profile=$($debug.profile), model=$($debug.model), baseURL=$($debug.baseURL), hasApiKey=$($debug.hasApiKey)"
  } catch {
    Write-Warning "Hermes LLM debug endpoint is not available yet: $($_.Exception.Message)"
  }
}

function Test-OpenAiCompatibleChat {
  param(
    [string]$ActivePath,
    [string]$SecretsPath
  )
  $active = Read-EnvFile -Path $ActivePath
  $secrets = Read-EnvFile -Path $SecretsPath
  $baseUrl = [string]$active["OPENAI_BASE_URL"]
  $baseUrl = $baseUrl.TrimEnd("/")
  $model = $active["OPENAI_MODEL"]
  $apiKeyEnv = [string]$active["HERMES_LLM_API_KEY_ENV"]
  $apiKey = $secrets[$apiKeyEnv]
  if (-not $baseUrl -or -not $model -or -not $apiKeyEnv -or -not $apiKey) {
    throw "Active LLM configuration or referenced secret is incomplete. Run set first."
  }
  $apiMode = [string]$active["HERMES_LLM_API_MODE"]
  if ($apiMode -eq "codex_responses") {
    $body = @{
      model = $model
      input = "Reply with OK."
      max_output_tokens = 8
    } | ConvertTo-Json -Depth 8
    $uri = "$baseUrl/responses"
  } else {
    $body = @{
      model = $model
      messages = @(@{
        role = "user"
        content = "Reply with OK."
      })
      temperature = 0
      max_tokens = 8
    } | ConvertTo-Json -Depth 8
    $uri = "$baseUrl/chat/completions"
  }
  $headers = @{
    Authorization = "Bearer $apiKey"
    "Content-Type" = "application/json"
  }
  $response = Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Body $body -TimeoutSec 60
  $text = if ($apiMode -eq "codex_responses") { $response.output_text } else { $response.choices[0].message.content }
  Write-Host "LLM smoke test: model=$model, apiMode=$apiMode, response=$text"
}

function Set-HermesLlmProfile {
  param(
    [string]$TargetProfileId,
    [switch]$SkipRestart,
    [switch]$SkipTest
  )
  if (-not $TargetProfileId) {
    $TargetProfileId = $profilesDoc.defaultProfileId
  }
  $profile = Find-Profile -ProfilesDoc $profilesDoc -Id $TargetProfileId
  Save-ProvidedSecrets -SecretsPath $secretsPath -DeepSeek $DeepSeekApiKey -Zhipu $ZhipuApiKey -GenericApiKey $ApiKey -GenericApiKeyName $profile.apiKeyEnv
  $secrets = Read-EnvFile -Path $secretsPath
  $apiKey = $secrets[$profile.apiKeyEnv]
  if (-not $apiKey -or (Test-PlaceholderApiKey -Value $apiKey)) {
    $secure = Read-Host -Prompt "Enter API key for $($profile.apiKeyEnv)" -AsSecureString
    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
      $apiKey = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
    } finally {
      [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
    }
    Save-ProvidedSecrets -SecretsPath $secretsPath -DeepSeek "" -Zhipu "" -GenericApiKey $apiKey -GenericApiKeyName $profile.apiKeyEnv
  }
  if ($profile.id -eq "gpt-5-6-terra") {
    Update-HermesConfig -Profile $profile -Root $InstallDir
  }
  Write-ActiveProfile -Profile $profile -ActivePath $activePath
  Write-Host "Active Hermes LLM profile set to $($profile.id) ($($profile.model))."
  if (-not $SkipRestart) {
    Restart-HermesTask
    Test-HermesHealth -WorkerEnvPath $workerEnvPath
  }
  if (-not $SkipTest) {
    Test-OpenAiCompatibleChat -ActivePath $activePath -SecretsPath $secretsPath
  }
}

function Get-ActiveProfileId {
  $active = Read-EnvFile -Path $activePath
  return [string]$active["HERMES_LLM_PROFILE"]
}

function Write-Menu {
  param(
    [object[]]$Profiles,
    [int]$SelectedIndex
  )
  Clear-Host
  $activeProfileId = Get-ActiveProfileId
  Write-Host "Hermes LLM Profile Switcher" -ForegroundColor Cyan
  Write-Host "Install dir: $InstallDir"
  Write-Host ""
  Write-Host "Use Up/Down to choose, Enter to switch, T to test current profile, R to refresh, Q/Esc to quit."
  Write-Host ""
  for ($index = 0; $index -lt $Profiles.Count; $index += 1) {
    $profile = $Profiles[$index]
    $cursor = if ($index -eq $SelectedIndex) { ">" } else { " " }
    $active = if ($profile.id -eq $activeProfileId) { "*" } else { " " }
    $line = "{0} {1} {2,-20} {3,-22} {4}" -f $cursor, $active, $profile.id, $profile.model, $profile.baseURL
    if ($index -eq $SelectedIndex) {
      Write-Host $line -ForegroundColor Black -BackgroundColor Gray
    } elseif ($profile.id -eq $activeProfileId) {
      Write-Host $line -ForegroundColor Green
    } else {
      Write-Host $line
    }
  }
  Write-Host ""
  Write-Host "* marks the active profile loaded from hermes-llm.active.env."
}

function Start-HermesLlmMenu {
  $profiles = @($profilesDoc.profiles)
  if (-not $profiles.Count) {
    throw "No Hermes LLM profiles are configured."
  }
  $activeProfileId = Get-ActiveProfileId
  $selectedIndex = 0
  for ($index = 0; $index -lt $profiles.Count; $index += 1) {
    if ($profiles[$index].id -eq $activeProfileId) {
      $selectedIndex = $index
      break
    }
  }

  while ($true) {
    Write-Menu -Profiles $profiles -SelectedIndex $selectedIndex
    $key = [Console]::ReadKey($true)
    if ($key.Key -eq [ConsoleKey]::UpArrow) {
      $selectedIndex = ($selectedIndex + $profiles.Count - 1) % $profiles.Count
      continue
    }
    if ($key.Key -eq [ConsoleKey]::DownArrow) {
      $selectedIndex = ($selectedIndex + 1) % $profiles.Count
      continue
    }
    if ($key.Key -eq [ConsoleKey]::Escape -or $key.Key -eq [ConsoleKey]::Q) {
      Clear-Host
      Write-Host "Hermes LLM profile switcher closed."
      return
    }
    if ($key.Key -eq [ConsoleKey]::R) {
      continue
    }
    if ($key.Key -eq [ConsoleKey]::T) {
      Clear-Host
      Test-HermesHealth -WorkerEnvPath $workerEnvPath
      Test-OpenAiCompatibleChat -ActivePath $activePath -SecretsPath $secretsPath
      Write-Host ""
      Write-Host "Press any key to return to the menu..."
      [Console]::ReadKey($true) | Out-Null
      continue
    }
    if ($key.Key -eq [ConsoleKey]::Enter) {
      Clear-Host
      $target = $profiles[$selectedIndex]
      Write-Host "Switching Hermes LLM profile to $($target.id)..."
      Set-HermesLlmProfile -TargetProfileId $target.id
      Write-Host ""
      Write-Host "Press any key to return to the menu..."
      [Console]::ReadKey($true) | Out-Null
      continue
    }
  }
}

$configDir = Get-ConfigDir -Root $InstallDir
$profilesPath = Sync-ProfilesFile -Root $InstallDir
$profilesDoc = Load-Profiles -Path $profilesPath
$secretsPath = Join-Path $configDir "hermes-llm-secrets.env"
$activePath = Join-Path $configDir "hermes-llm.active.env"
$workerEnvPath = Join-Path $InstallDir "software-doc-worker.env"

if ($Action -eq "menu") {
  Save-ProvidedSecrets -SecretsPath $secretsPath -DeepSeek $DeepSeekApiKey -Zhipu $ZhipuApiKey -GenericApiKey "" -GenericApiKeyName ""
  Start-HermesLlmMenu
  exit 0
}

if ($Action -eq "list") {
  Write-Host "Available Hermes LLM profiles:"
  foreach ($profile in @($profilesDoc.profiles)) {
    $defaultMark = if ($profile.id -eq $profilesDoc.defaultProfileId) { " (default)" } else { "" }
    Write-Host "- $($profile.id)$defaultMark : $($profile.displayName) [$($profile.model)] $($profile.baseURL)"
  }
  exit 0
}

if ($Action -eq "init") {
  Save-ProvidedSecrets -SecretsPath $secretsPath -DeepSeek $DeepSeekApiKey -Zhipu $ZhipuApiKey -GenericApiKey "" -GenericApiKeyName ""
  Write-Host "Hermes LLM config initialized: $configDir"
  exit 0
}

if ($Action -eq "show") {
  $active = Read-EnvFile -Path $activePath
  if (-not $active.Count) {
    Write-Host "No active Hermes LLM profile has been selected."
    Write-Host "Run: .\Switch-HermesLlmProfile.ps1 -Action set -ProfileId $($profilesDoc.defaultProfileId)"
    exit 0
  }
  Write-Host "Active Hermes LLM profile:"
  Write-Host "profile=$($active["HERMES_LLM_PROFILE"])"
  Write-Host "provider=$($active["HERMES_LLM_PROVIDER"])"
  Write-Host "model=$($active["OPENAI_MODEL"])"
  Write-Host "baseURL=$($active["OPENAI_BASE_URL"])"
  Write-Host "apiMode=$($active["HERMES_LLM_API_MODE"])"
  $secrets = Read-EnvFile -Path $secretsPath
  Write-Host "hasApiKey=$([bool]$secrets[$active["HERMES_LLM_API_KEY_ENV"]])"
  exit 0
}

if ($Action -eq "set") {
  Set-HermesLlmProfile -TargetProfileId $ProfileId -SkipRestart:$NoRestart -SkipTest:$NoTest
  exit 0
}

if ($Action -eq "test") {
  Test-HermesHealth -WorkerEnvPath $workerEnvPath
  Test-OpenAiCompatibleChat -ActivePath $activePath -SecretsPath $secretsPath
  exit 0
}
